config/routes.rb
Rails.application.routes.draw do
  resources :logs

  resources :notifications

  resources :scrapers

  mount Upmin::Engine => '/karyakarta'

  resources :users
  root to: 'visitors#index'
  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure'
end

app/models/scraper.rb
class Scraper < ActiveRecord::Base
  belongs_to :user
  has_many :logs
  has_many :notifications

  SCHEDULES = %w[every_15m every_30m every_1h every_2h every_5h every_12h every_1d every_2d every_7d
                 midnight 1am 2am 3am 4am 5am 6am 7am 8am 9am 10am 11am noon 1pm 2pm 3pm 4pm 5pm 6pm 7pm 8pm 9pm 10pm 11pm never]

  EVENT_RETENTION_SCHEDULES = [["Forever", 0], ["1 day", 1], *([2, 3, 4, 5, 7, 14, 21, 30, 45, 90, 180, 365].map {|n| ["#{n} days", n] })]

  before_save :set_next_run_time
  scope :pending_jobs, -> { where("next_run_time < ?", Time.zone.now) }

  validates :url, format: URI::regexp(%w(http https)), presence: true
  validates :name, presence: true
  validates :schedule, presence: true
  validates :extract, presence: true
  validates :target_element, presence: true

  def self.execute_jobs
    Scraper.pending_jobs.each do |scraper|
      begin
        scraper.status = true
        scraper.check
      rescue StandardError => ex
        scraper.status = false
        scraper.log ex.message
      end
      scraper.last_check = Time.zone.now
      scraper.set_next_run_time
      scraper.save
    end
  end

  def check
    log "running scraper #{name}"
    faraday = Faraday.new(:url => url)
    response = faraday.get(url)
    raise "Failed: #{response.inspect}" unless response.success?
    body = response.body
    doc = Nokogiri::HTML(body)
    output = extract_xml(doc)

    log output.to_json
    notify_if_changed(output)
  end

  def set_next_run_time
    if new_record?
      self.next_run_time = Time.zone.now
      return
    end

    # set only if schedule is changed
    # return if schedule == schedule_was

    self.next_run_time = case schedule
                         when /never/
                           puts "never"
                           nil
                         when /every_(\d+)(m|h|d)/
                           puts "matches every #{$1} #{$2}"
                           case $2
                           when 'm'
                             Time.now + $1.to_i.minutes
                           when 'h'
                             Time.now + $1.to_i.hours
                           when 'd'
                             Time.now + $1.to_i.days
                           end
                         when /midnight/
                           puts "00:00"
                           Chronic.parse("today midnight")
                         when /noon/
                           puts "12:00"
                           if Time.now.noon < Time.now # already past noon
                             (Time.now + 1.day).noon
                           else
                             Time.now.noon
                           end
                         when /(am|pm)/
                           puts $1
                           today = Chronic.parse("today at " + schedule)
                           (today <= Time.now) ? Chronic.parse("tomorrow at " + schedule) : today
                         end
  end

  def log(message)
    logs.create(message: message)
  end

  private

    def notify_if_changed(output)
      last = notifications.order('id desc').first
      # binding.pry

      if last.present?
        return if last.output.downcase.gsub(/\s/, "") == output.to_json.downcase.gsub(/\s/, "")
      end
      self.last_notification = Time.zone.now
      notifications.create(output: output.to_json)
    end

    def extract_xml(doc)
      extract_each(doc) { |name|
        nodes = doc.css(target_element)
        # binding.pry
        result = nodes.map { |node|
          xpath = name == "text" ? "text()" : name
          case value = node.xpath(xpath)
          when Float
            # Node#xpath() returns any numeric value as float;
            # convert it to integer as appropriate.
            value = value.to_i if value.to_i == value
          end
          protocol = url.match(/^(https?)/).to_s
          value = value.text()
          value = if value =~ /^\/\//
                    value.gsub(/^\/\//, "#{protocol}://")
                  else
                    value.gsub(/(\W){2,}/m, '\1')
                  end
          value.gsub(/(https?)\//, '\1://')
        }
        # log "Extracting #{name}: #{result}"

        # case
        # when css = extraction_details['css']
        #   nodes = doc.css(css)
        # when xpath = extraction_details['xpath']
        #   doc.remove_namespaces! # ignore xmlns, useful when parsing atom feeds
        #   nodes = doc.xpath(xpath)
        # else
        #   raise '"css" or "xpath" is required for HTML or XML extraction'
        # end

        # case nodes
        # when Nokogiri::XML::NodeSet
        #   result = nodes.map { |node|
        #     case value = node.xpath(extraction_details['value'])
        #     when Float
        #       # Node#xpath() returns any numeric value as float;
        #       # convert it to integer as appropriate.
        #       value = value.to_i if value.to_i == value
        #     end
        #     value.to_s
        #   }
        # else
        #   raise "The result of HTML/XML extraction was not a NodeSet"
        # end
        result
      }
    end

    def extract_each(doc, &block)
      extract.split(",").each_with_object({}) { |(name), output|
        output[name.strip] = block.call(name)
      }
    end

    def faraday
      @faraday ||= Faraday.new { |builder|
        builder.headers[:user_agent] = 'Mozilla/5.0 (Windows; U; Windows NT 6.1; tr-TR) AppleWebKit/533.20.25 (KHTML, like Gecko) Version/5.0.4 Safari/533.20.27'

        builder.use FaradayMiddleware::FollowRedirects
        builder.request :url_encoded
      }
    end

end

app/controllers/scrapers_controller.rb
class ScrapersController < ApplicationController
  respond_to :html
  before_filter :authenticate_user!
  before_action :set_scraper, only: [:show, :edit, :update, :destroy]

  def index
    @scrapers = current_user.scrapers
    respond_with(@scrapers)
  end

  def show
    respond_with(@scraper)
  end

  def new
    @scraper = Scraper.new
    respond_with(@scraper)
  end

  def edit
  end

  def create
    @scraper = Scraper.new(scraper_params)
    @scraper.user_id = current_user.id
    @scraper.save
    respond_with(@scraper)
  end

  def update
    @scraper.update(scraper_params)
    respond_with(@scraper)
  end

  def destroy
    @scraper.destroy
    respond_with(@scraper)
  end

  private

    def set_scraper
      @scraper = Scraper.find(params[:id])
    end

    def scraper_params
      params.require(:scraper).permit(:name, :url, :target_element, :schedule, :extract, :user_id, :subject)
    end
end

app/views/scrapers/_form.html.haml
= simple_form_for(@scraper) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name, placeholder: 'Name of your scraper.', hint: 'e.g. Hacker News top story'
    = f.input :url, placeholder: 'URL of the page, you want to scrape.', hint: 'e.g. https://news.ycombinator.com/'
    = f.input :target_element, placeholder: 'CSS selector for the target element in page.', hint: 'e.g. tr:nth-child(1) .title a'
    .alert.alert-info(style="width:30%;")
      You can use
      = link_to "Selector Gadget", "http://selectorgadget.com/"
      to find the CSS selectors

    = f.input :schedule, collection: Scraper::SCHEDULES.map {|s| [s.humanize.titleize, s] }, hint: 'How often you want to scrape the page?'
    = f.input :extract, as: :text, placeholder: 'Comma separated XPath expressions, you want to extract.', hint: "e.g. @href, text()"
    = f.input :subject, placeholder: 'XPath expression to use as email subject', hint: 'e.g. //*[@class="dotd-title"]'

  .form-actions
    = f.button :submit

app/views/scrapers/_list.html.haml
%h1 Scrapers

-if @scrapers.empty?
  %h2 No Scrapers yet! You want to create new?
-else
  %table.table.table-striped
    %tr
      %th Name
      %th Url
      %th Schedule
      %th Next Check
      %th Last check
      %th Last notification
      %th Last Status
      %th Logs
      %th Notifications
      %th
      %th
    -if @scrapers.present?
      - @scrapers.each do |scraper|
        %tr
          %td= link_to scraper.name, scraper
          %td= scraper.url
          %td= scraper.schedule.humanize.titleize
          %td= humanize_time scraper.next_run_time
          %td= humanize_time scraper.last_check
          %td= humanize_time scraper.last_notification
          %td= raw success_fail(scraper.status)
          %td= link_to 'Logs', logs_path( :params => {:scraper_id => scraper.id})
          %td= link_to 'Notifications', notifications_path( :params => {:scraper_id => scraper.id})

app/views/scrapers/edit.html.haml
%h1 Editing scraper

= render 'form'

= link_to 'Show', @scraper
\|
= link_to 'Back', scrapers_path

app/views/scrapers/index.html.haml
= render "list"

%br

= link_to 'New Scraper', new_scraper_path

app/views/scrapers/new.html.haml
%h1 New scraper

= render 'form'

= link_to 'Back', scrapers_path

app/views/scrapers/show.html.haml
%h2 Scraper: #{@scraper.name}

%table.table.table-striped
  %tr
    %td(width="15%")
      %b
        Name
    %td= @scraper.name
    %td
      %b
        Url
    %td= @scraper.url

  %tr
    %td(width="15%")
      %b
        Target Element
    %td= @scraper.target_element
    %td
      %b
        Schedule
    %td= @scraper.schedule.humanize.titleize

  %tr
    %td
      %b
        Last check
    %td= humanize_time(@scraper.last_check)
    %td
      %b
        Next run time
    %td= humanize_time(@scraper.next_run_time)

  %tr
    %td
      %b
        Last notification
    %td= humanize_time(@scraper.last_notification)
    %td
      %b
        Extract
    %td= @scraper.extract

  %tr
    %td
      %b
        Last status
    %td= raw success_fail(@scraper.status)
    %td
    %td

  %tr
    %td
      %b
        Notifications
    %td=link_to 'Notifications', notifications_path( :params => {:scraper_id => @scraper.id})
    %td
      %b
        Logs
    %td=link_to 'Logs', logs_path( :params => {:scraper_id => @scraper.id})

= link_to 'Edit', edit_scraper_path(@scraper)
\|
= link_to 'Back', scrapers_path
\|
= link_to 'Destroy', @scraper, :method => :delete, :data => { :confirm => 'Are you sure?' }