config/routes.rb
Rails.application.routes.draw do
  resources :logs

  resources :notifications

  resources :scrapers

  mount Upmin::Engine => '/karyakarta'

  resources :users
  root to: 'visitors#index'
  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure'
end

app/models/notification.rb
class Notification < ActiveRecord::Base
  belongs_to :scraper
  after_create :notify_user
  paginates_per 25

  private
    def notify_user
      puts "notify: #{scraper.user.email}"
      Notifier.notify(scraper.user, self).deliver
    end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :set_notification, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  # GET /notifications
  # GET /notifications.json
  def index
    if params[:scraper_id].present?
      scraper = Scraper.find(params[:scraper_id])
      @notifications = scraper.notifications.order(created_at: :desc).page params[:page]
    else  
      @notifications = current_user.notifications.order(created_at: :desc).page params[:page]
    end
  end

  # GET /notifications/1
  # GET /notifications/1.json
  def show
  end

  # GET /notifications/new
  def new
    @notification = Notification.new
  end

  # GET /notifications/1/edit
  def edit
  end

  # POST /notifications
  # POST /notifications.json
  def create
    @notification = Notification.new(notification_params)

    respond_to do |format|
      if @notification.save
        format.html { redirect_to @notification, notice: 'Notification was successfully created.' }
        format.json { render :show, status: :created, location: @notification }
      else
        format.html { render :new }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notifications/1
  # PATCH/PUT /notifications/1.json
  def update
    respond_to do |format|
      if @notification.update(notification_params)
        format.html { redirect_to @notification, notice: 'Notification was successfully updated.' }
        format.json { render :show, status: :ok, location: @notification }
      else
        format.html { render :edit }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notifications/1
  # DELETE /notifications/1.json
  def destroy
    @notification.destroy
    respond_to do |format|
      format.html { redirect_to notifications_url, notice: 'Notification was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notification
      @notification = Notification.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def notification_params
      params.require(:notification).permit(:output, :scraper_id, :notification_type, :sent)
    end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_form.html.haml
= simple_form_for(@notification) do |f|
  = f.error_notification

  .form-inputs
    = f.input :output
    = f.association :scraper
    = f.input :notification_type
    = f.input :sent

  .form-actions
    = f.button :submit

app/views/notifications/edit.html.haml
%h1 Editing notification

= render 'form'

= link_to 'Show', @notification
\|
= link_to 'Back', notifications_path

app/views/notifications/index.html.haml
%h1  Notifications
%h6.lead.small.text-primary
  = " for " + @notifications.first.scraper.name if params[:scraper_id].present? and @notifications.present?
%table.table.table-striped
  %tr
    %th Scraper
    %th Output
    %th Time

  - @notifications.each do |notification|
    %tr
      %td= link_to notification.scraper.name, notification.scraper
      %td= notification.output
      %td= distance_of_time_in_words_to_now(notification.created_at) + " ago"
%br
= paginate @notifications

app/views/notifications/new.html.haml
%h1 New notification

= render 'form'

= link_to 'Back', notifications_path

app/views/notifications/show.html.haml
%p#notice= notice

%p
  %b Output:
  = @notification.output
%p
  %b Scraper:
  = @notification.scraper
%p
  %b Notification type:
  = @notification.notification_type
%p
  %b Sent:
  = @notification.sent

= link_to 'Edit', edit_notification_path(@notification)
\|
= link_to 'Back', notifications_path