config/routes.rb
Rails.application.routes.draw do
  resources :logs

  resources :notifications

  resources :scrapers

  mount Upmin::Engine => '/karyakarta'

  resources :users
  root to: 'visitors#index'
  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure'
end

app/models/log.rb
class Log < ActiveRecord::Base
  belongs_to :scraper
  paginates_per 25
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
  before_action :set_log, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  # GET /logs
  # GET /logs.json
  def index
    if params[:scraper_id].present?
      scraper = Scraper.find(params[:scraper_id])
      @logs = scraper.logs.order(created_at: :desc).page params[:page]
      # @logs.
    else  
      @logs = current_user.logs.order(created_at: :desc).page params[:page]
      # @logs
    end
  end

  # GET /logs/1
  # GET /logs/1.json
  def show
  end

  # GET /logs/new
  def new
    @log = Log.new
  end

  # GET /logs/1/edit
  def edit
  end

  # POST /logs
  # POST /logs.json
  def create
    @log = Log.new(log_params)

    respond_to do |format|
      if @log.save
        format.html { redirect_to @log, notice: 'Log was successfully created.' }
        format.json { render :show, status: :created, location: @log }
      else
        format.html { render :new }
        format.json { render json: @log.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /logs/1
  # PATCH/PUT /logs/1.json
  def update
    respond_to do |format|
      if @log.update(log_params)
        format.html { redirect_to @log, notice: 'Log was successfully updated.' }
        format.json { render :show, status: :ok, location: @log }
      else
        format.html { render :edit }
        format.json { render json: @log.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /logs/1
  # DELETE /logs/1.json
  def destroy
    @log.destroy
    respond_to do |format|
      format.html { redirect_to logs_url, notice: 'Log was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_log
      @log = Log.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def log_params
      params.require(:log).permit(:message, :scraper_id, :extra)
    end
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/views/logs/_form.html.haml
= simple_form_for(@log) do |f|
  = f.error_notification

  .form-inputs
    = f.input :message
    = f.association :scraper
    = f.input :extra

  .form-actions
    = f.button :submit

app/views/logs/edit.html.haml
%h1 Editing log

= render 'form'

= link_to 'Show', @log
\|
= link_to 'Back', logs_path

app/views/logs/index.html.haml
%h1 Logs
%h6.lead.small.text-primary
  = " for " + @logs.first.scraper.name if params[:scraper_id].present? and @logs.present?
%table.table.table-striped
  %tr
    %th Scraper
    %th Message
    %th Time

  - @logs.each do |log|
    %tr
      %td= link_to log.scraper.name, log.scraper
      %td= log.message
      %td= distance_of_time_in_words_to_now(log.created_at)  + " ago"
      
%br
= paginate @logs

app/views/logs/new.html.haml
%h1 New log

= render 'form'

= link_to 'Back', logs_path

app/views/logs/show.html.haml
%p#notice= notice

%p
  %b Message:
  = @log.message
%p
  %b Scraper:
  = @log.scraper
%p
  %b Extra:
  = @log.extra

= link_to 'Edit', edit_log_path(@log)
\|
= link_to 'Back', logs_path