config/routes.rb
Rails.application.routes.draw do
  resources :logs

  resources :notifications

  resources :scrapers

  mount Upmin::Engine => '/karyakarta'

  resources :users
  root to: 'visitors#index'
  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure'
end

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
-if flash.present?
  %section.sectionflash
    - flash.each do |name, msg|
      - if msg.is_a?(String)
        %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
          %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
          = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/amoeba.html.haml
!!!
/[if lt IE 7] <html class="no-js lt-ie9 lt-ie8 lt-ie7">
/[if IE 7] <html class="no-js lt-ie9 lt-ie8">
/[if IE 8] <html class="no-js lt-ie9">
/ [if gt IE 8]><!
%html.no-js
  / <![endif]
  %head
    / BASICS
    %meta{:charset => "utf-8"}/
    %meta{:content => "IE=edge,chrome=1", "http-equiv" => "X-UA-Compatible"}/
    %title Page Poller - Watch web pages for changes and get notified when it changes.
    %meta{:content => "", :name => "description"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = csrf_meta_tags

  %body
    %section#header.appear
    .navbar.navbar-fixed-top{"data-0" => "line-height:100px; height:100px; background-color:rgba(0,0,0,0.3);", "data-300" => "line-height:60px; height:60px; background-color:rgba(0,0,0,1);", :role => "navigation"}
      .container
        .navbar-header
          %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
            %span.fa.fa-bars.color-white
          %h1
            %a.navbar-brand{"data-0" => "line-height:90px;", "data-300" => "line-height:50px;", :href => "/"}
              %i.fa.fa-code
              Page Poller

        .navbar-collapse.collapse
          %ul.nav.navbar-nav{"data-0" => "margin-top:20px;", "data-300" => "margin-top:5px;"}
            %li
              %a{:href => "/"} Home
            -if current_user.present?
              %li
                = link_to "Scrapers", scrapers_path
              %li
                = link_to "Notifications", notifications_path
              %li
                = link_to "Logs", logs_path
              %li
                
              %li.dropdown
                %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                  = current_user.name
                  %span.caret
                %ul.dropdown-menu{:role => "menu"}
                  %li
                    = link_to "Profile", current_user
                  %li
                    = link_to "Sign out", signout_path
            -else
              %li
                = link_to "Log In With Github", signin_path

    =render 'layouts/messages'
    -if controller.controller_name == "visitors"
      - if current_user.nil?
        %section.featured
          .container
            .row.mar-bot40
              = yield
      -else
        %section#section-services.section.bg-white
          .container
            .row.mar-bot40
              = yield
    -else
      / services
      %section#section-services.section.pad-bot30.bg-white
        .container
          .row.mar-bot40
            = yield
  
    %section#footer.section.footer
      .container
        .row.animated.opacity.mar-bot20{"data-andown" => "fadeIn", "data-animation" => "animation"}
          .col-sm-12.align-center
        .row.align-center.copyright
          .col-sm-12
            %p.lead
              Brought to you by:
              %a{:href => "http://cuberoot.in"} Cube Root Software
              , Theme  - by
              %a{:href => "http://bootstraptaste.com"} Bootstraptaste
    #rumble2014{:style => "position: fixed; display: block; width: 100%; z-index: 99999; bottom: 0px; left: 0px; padding: 10px 0px; text-align: center; margin: 0px; color: rgb(176, 176, 176); background-color: rgb(22, 22, 22);"}
      %span
        You can
        %a{:href => "http://railsrumble.com/?view=http://immense-bayou-8081.herokuapp.com/", :style => "color: rgb(255, 255, 255); font-weight: bolder; text-decoration: none;"} vote for us
        in the
        = succeed "!" do
          %a{:href => "http://railsrumble.com", :style => "color: rgb(255, 255, 255); font-weight: bolder; text-decoration: none;"} 2014 Rails Rumble
      %span#rumbleCloseButton{:style => "position: absolute; right: 8px; cursor: pointer; top: 8px;"} x

    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    %script{:charset => "utf-8", :type => "text/javascript"}
      var _swell_site_ids = _swell_site_ids || [];
      _swell_site_ids.push('ca23b576');
      (function() {
      var s = document.createElement('script');
      s.type = 'text/javascript';
      s.async = true;
      s.src = '//df50assd5876f.cloudfront.net/assets/hello-3b9181727ebdc6002c5bb5da48a2257f.js';
      ( document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0] ).appendChild( s );
      })();
    %noscript
      %img{:src => "//heyswell.com/v1/hello.gif?sites=ca23b576&javascript=0"}/

        

app/views/layouts/email.html.haml
!!!
%html(xmlns="http://www.w3.org/1999/xhtml")
  %head
    %meta(content="width=device-width" name="viewport")/
    %meta(content="text/html; charset=UTF-8" http-equiv="Content-Type")/
    %title Page Poller
    %link(href="stylesheets/email.css" rel="stylesheet" type="text/css")/
    :css
      /* -------------------------------------
          GLOBAL
      ------------------------------------- */
      * {
        margin:0;
        padding:0;
      }
      * { font-family: "Helvetica Neue", "Helvetica", Helvetica, Arial, sans-serif; }

      img {
        max-width: 100%;
      }
      .collapse {
        margin:0;
        padding:0;
      }
      body {
        -webkit-font-smoothing:antialiased;
        -webkit-text-size-adjust:none;
        width: 100%!important;
        height: 100%;
      }


      /* -------------------------------------
          ELEMENTS
      ------------------------------------- */
      a { color: #2BA6CB;}

      .btn {
        text-decoration:none;
        color: #FFF;
        background-color: #666;
        padding:10px 16px;
        font-weight:bold;
        margin-right:10px;
        text-align:center;
        cursor:pointer;
        display: inline-block;
      }

      p.callout {
        padding:15px;
        background-color:#ECF8FF;
        margin-bottom: 15px;
      }
      .callout a {
        font-weight:bold;
        color: #2BA6CB;
      }

      table.social {
      /*  padding:15px; */
        background-color: #ebebeb;

      }
      .social .soc-btn {
        padding: 3px 7px;
        font-size:12px;
        margin-bottom:10px;
        text-decoration:none;
        color: #FFF;font-weight:bold;
        display:block;
        text-align:center;
      }
      a.fb { background-color: #3B5998!important; }
      a.tw { background-color: #1daced!important; }
      a.gp { background-color: #DB4A39!important; }
      a.ms { background-color: #000!important; }

      .sidebar .soc-btn {
        display:block;
        width:100%;
      }

      /* -------------------------------------
          HEADER
      ------------------------------------- */
      table.head-wrap { width: 100%;}

      .header.container table td.logo { padding: 15px; }
      .header.container table td.label { padding: 15px; padding-left:0px;}


      /* -------------------------------------
          BODY
      ------------------------------------- */
      table.body-wrap { width: 100%;}


      /* -------------------------------------
          FOOTER
      ------------------------------------- */
      table.footer-wrap { width: 100%;  clear:both!important;
      }
      .footer-wrap .container td.content  p { border-top: 1px solid rgb(215,215,215); padding-top:15px;}
      .footer-wrap .container td.content p {
        font-size:10px;
        font-weight: bold;

      }


      /* -------------------------------------
          TYPOGRAPHY
      ------------------------------------- */
      h1,h2,h3,h4,h5,h6 {
      font-family: "HelveticaNeue-Light", "Helvetica Neue Light", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif; line-height: 1.1; margin-bottom:15px; color:#000;
      }
      h1 small, h2 small, h3 small, h4 small, h5 small, h6 small { font-size: 60%; color: #6f6f6f; line-height: 0; text-transform: none; }

      h1 { font-weight:200; font-size: 44px;}
      h2 { font-weight:200; font-size: 37px;}
      h3 { font-weight:500; font-size: 27px;}
      h4 { font-weight:500; font-size: 23px;}
      h5 { font-weight:900; font-size: 17px;}
      h6 { font-weight:900; font-size: 14px; text-transform: uppercase; color:#444;}

      .collapse { margin:0!important;}

      p, ul {
        margin-bottom: 10px;
        font-weight: normal;
        font-size:14px;
        line-height:1.6;
      }
      p.lead { font-size:17px; }
      p.last { margin-bottom:0px;}

      ul li {
        margin-left:5px;
        list-style-position: inside;
      }

      /* -------------------------------------
          SIDEBAR
      ------------------------------------- */
      ul.sidebar {
        background:#ebebeb;
        display:block;
        list-style-type: none;
      }
      ul.sidebar li { display: block; margin:0;}
      ul.sidebar li a {
        text-decoration:none;
        color: #666;
        padding:10px 16px;
      /*  font-weight:bold; */
        margin-right:10px;
      /*  text-align:center; */
        cursor:pointer;
        border-bottom: 1px solid #777777;
        border-top: 1px solid #FFFFFF;
        display:block;
        margin:0;
      }
      ul.sidebar li a.last { border-bottom-width:0px;}
      ul.sidebar li a h1,ul.sidebar li a h2,ul.sidebar li a h3,ul.sidebar li a h4,ul.sidebar li a h5,ul.sidebar li a h6,ul.sidebar li a p { margin-bottom:0!important;}



      /* ---------------------------------------------------
          RESPONSIVENESS
          Nuke it from orbit. It's the only way to be sure.
      ------------------------------------------------------ */

      /* Set a max-width, and make it display as block so it will automatically stretch to that width, but will also shrink down on a phone or something */
      .container {
        display:block!important;
        max-width:820px!important;
        margin:0 auto!important; /* makes it centered */
        clear:both!important;
      }

      /* This should also be a block element, so that it will fill 100% of the .container */
      .content {
        padding:15px;
        max-width:820px;
        margin:0 auto;
        display:block;
      }

      /* Let's make sure tables in the content area are 100% wide */
      .content table { width: 100%; }


      /* Odds and ends */
      .column {
        width: 300px;
        float:left;
      }
      .column tr td { padding: 15px; }
      .column-wrap {
        padding:0!important;
        margin:0 auto;
        max-width:820px!important;
      }
      .column table { width:100%;}
      .social .column {
        width: 280px;
        min-width: 279px;
        float:left;
      }

      /* Be sure to place a .clear element after each set of columns, just to be safe */
      .clear { display: block; clear: both; }


      /* -------------------------------------------
          PHONE
          For clients that support media queries.
          Nothing fancy.
      -------------------------------------------- */
      @media only screen and (max-width: 820px) {

        a[class="btn"] { display:block!important; margin-bottom:10px!important; background-image:none!important; margin-right:0!important;}

        div[class="column"] { width: auto!important; float:none!important;}

        table.social div[class="column"] {
          width:auto!important;
        }

      }
  %body(bgcolor="#eee")
    %table.body-wrap
      %tbody
        %tr
          %td
          %td.container(bgcolor="#FFFFFF")
            .content
              %table
                %tbody
                  %tr
                    %td
                      %div(height="100%")
                        = yield
          %td
    %table.footer-wrap
      %tbody
        %tr
          %td
          %td.container
            .content
              %table
                %tbody
                  %tr
                    %td(align="center")
                      %p
                        %a(href="http://pagepoller.r14.railsrumble.com/" rel="noreferrer") Your account
                        |
                        %a(href="http://pagepoller.r14.railsrumble.com/" rel="noreferrer")
                          %unsubscribe Unsubscribe
          %td